export const CartActionTypes = {
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  REMOVE_ITEM_ALL: 'REMOVE_ITEM_ALL',
  RESET_CART: 'RESET_CART',
  ADD_ORDER: 'ADD_ORDER'
  // RE_ITEM: 'RE_ITEM'
};
